title: JWT Lesson
description: "12/19/23"
owner_name: Aliya Tang
github_username: aliyatang
github_repo: "LessonJWT"
baseurl: "/LessonJWT"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/LessonJWT"}
    - { platform: github, user_url: "https://github.com/aliyatang"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
